# Generated by Django 5.2.5 on 2025-08-13 04:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_visible_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductViewMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_id'], name='products_pr_product_c4015d_idx'), models.Index(fields=['created_at'], name='products_pr_created_5b90b3_idx')],
            },
        ),
    ]
